
-- 1 Find the total revenue generated for each product category.

select
    p.category,
    SUM(o.quantity * o.price)
FROM
    orderdetails o
    JOIN products p ON o.productid = p.id
GROUP BY
    p.category;

-- 2 Identify the top 5 customers who have spent the most on delivered orders.
SELECT
    c.id,
    c.customername
FROM
    orders o
    INNER JOIN payment p ON p.orderid = o.id
    INNER JOIN customers c ON c.id = o.customerid
WHERE
    p.paymentdate < CURRENT_DATE
ORDER BY
    o.totalamount DESC
LIMIT
    5;

-- 3  Compute the month-over-month sales growth percentage.

SELECT
    date_trunc ('month', orderdate)
FROM
    orders
GROUP BY
    date_trunc ('month', orderdate);

-- 4  Find the average amount spent per order by each customer.
SELECT
    c.id,
    c.customername,
    AVG(o.totalamount)
FROM
    customers c
    INNER JOIN orders o ON c.id = o.customerid
GROUP BY
    o.id,
    c.id;

-- 5  Identify products where the stock quantity is below a given threshold.

SELECT
    *
FROM
    products
WHERE
    stockquantity < 200;


-- 6 Find the top 10 most frequently ordered products.
SELECT
    p.id,
    COUNT(od.id) AS nooforders
FROM
    orderdetails od
    JOIN products p on od.productid = p.id
GROUP BY
    p.id
ORDER BY
    nooforders DESC
LIMIT
    10;

-- 7 Calculate the percentage of customers who placed another order within 90 days of their first order
SELECT
    ROUND(
        (COUNT(DISTINCT o1.customerid) * 100.0) / COUNT(DISTINCT o2.customerid),
        2
    ) AS RepeatCustomerPercentage
FROM
    orders o1
    JOIN orders o2 ON o1.customerid = o2.customerid
    AND o1.orderdate > o2.orderdate
    AND o1.orderdate <= o2.orderdate + INTERVAL '90 days';

-- 8 Determine the percentage of total revenue generated by each payment method
SELECT
    paymentmethod,
    SUM(amount) as totalRevenue,
    (
        SUM(amount) * 100.0 / (
            SELECT
                SUM(amount)
            FROM
                payment
        )
    ) AS RevenuePercentage
FROM
    payment
GROUP BY
    paymentmethod;

-- 9 Find the average time taken for an order to move from ‘Pending’ to ‘Delivered’ status.

select
    o.id,
    o.orderdate,
    p.paymentdate,
    (p.paymentdate - o.orderdate) as difference
from
    orders o
    inner join payment p on o.id = p.orderid
order by
    o.id;

-- 10.  Calculate the percentage of customers who have made more than one purchase
SELECT
    (
        COUNT(DISTINCT customerid) * 100.0 / (
            SELECT
                COUNT(DISTINCT id)
            FROM
                customers
        )
    ) AS RepeatCustomerRate
FROM
    (
        SELECT
            customerid
        FROM
            orders
        GROUP BY
            customerid
        HAVING
            COUNT(id) > 1
    ) AS RepeatCustomers;